# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
