# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0003_auto_20170621_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
