# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0005_page_passive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='passive',
            field=models.BooleanField(default=False),
        ),
    ]
