# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0006_auto_20170628_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_canvas',
            field=models.BooleanField(default=True),
        ),
    ]
